// Generates src/data.js from @moishy/algsets, with cleanup + F2L verification.
import { oll } from '@moishy/algsets/oll';
import { pll } from '@moishy/algsets/pll';
import { applyMoves, invert, solvedCube, toFacelets, parseAlg } from '@moishy/cubing-core';
import { writeFileSync } from 'node:fs';

const str = (ms) =>
  ms.map((m) => m.family + (m.amount === 2 ? '2' : m.amount === 3 ? "'" : '')).join(' ');

// Merge consecutive turns of the same family, drop identities.
function simplify(alg) {
  const toks = alg.split(/\s+/).filter(Boolean);
  const out = [];
  for (const t of toks) {
    const base = t.replace(/['2]/g, '');
    const amt = t.includes("'") ? 3 : t.includes('2') ? 2 : 1;
    if (out.length && out[out.length - 1].base === base) {
      out[out.length - 1].amt = (out[out.length - 1].amt + amt) % 4;
    } else {
      out.push({ base, amt });
    }
  }
  return out
    .filter((o) => o.amt !== 0)
    .map((o) => o.base + (o.amt === 2 ? '2' : o.amt === 3 ? "'" : ''))
    .join(' ');
}

const F2L = [];
for (let i = 0; i < 9; i++) F2L.push(27 + i);
for (const b of [9, 18, 36, 45]) for (const i of [3, 4, 5, 6, 7, 8]) F2L.push(b + i);
const SOLVED = toFacelets(solvedCube());
const f2lOk = (alg) => {
  try {
    const X = applyMoves(solvedCube(), invert(parseAlg(alg)));
    const f = toFacelets(X);
    return F2L.every((i) => f[i] === SOLVED[i]);
  } catch (e) {
    return false;
  }
};

// Manual overrides (id -> alg). All are verified below.
const OLL_FIX = {
  'oll-52': "R U R' U R U' B U' B' R'",
};
const PLL_FIX = {
  e: "R U' R' D R U R' D' R U R' D R U' R' D'",
  na: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
  nb: "R' U R U' R' F' U' F R U R' F R' F' R U' R",
};

const build = (set, fix) =>
  set.cases.map((c) => {
    let alg = fix[c.id] ? simplify(fix[c.id]) : simplify(str(c.algs[0].moves));
    if (!f2lOk(alg)) {
      // fall back to any verified variant
      const v = c.algs.map((a) => simplify(str(a.moves))).find(f2lOk);
      if (!v) throw new Error('no F2L-preserving alg for ' + c.id);
      alg = v;
    }
    const id = c.id;
    const name =
      id === 'U' ? 'Y Permutation' : c.name || id;
    return { id, name, subset: c.subset || 'other', alg };
  });

const O = build(oll, OLL_FIX);
const P = build(pll, PLL_FIX);
for (const c of [...O, ...P]) {
  if (!f2lOk(c.alg)) throw new Error('F2L check failed: ' + c.id + ' ' + c.alg);
}
console.log('OLL', O.length, 'PLL', P.length, 'all F2L-preserving');

const header = `// AUTO-GENERATED by build-data.mjs. Do not edit by hand.
// Algorithms sourced from SpeedCubeDB (via @moishy/algsets), cleaned up and
// verified to preserve the bottom two layers (cross + F2L).
`;
const body =
  header +
  `export const OLL = ${JSON.stringify(O, null, 2)};\n\n` +
  `export const PLL = ${JSON.stringify(P, null, 2)};\n`;
writeFileSync('src/data.js', body);
console.log('wrote src/data.js');
