// AUTO-GENERATED by build-data.mjs. Do not edit by hand.
// Algorithms sourced from SpeedCubeDB (via @moishy/algsets), cleaned up and
// verified to preserve the bottom two layers (cross + F2L).
export const OLL = [
  {
    "id": "oll-1",
    "name": "OLL 1",
    "subset": "dot",
    "alg": "R U2 R2 F R F' U2 R' F R F'"
  },
  {
    "id": "oll-2",
    "name": "OLL 2",
    "subset": "dot",
    "alg": "f U R U' R' f' F U R U' R' F'"
  },
  {
    "id": "oll-3",
    "name": "OLL 3",
    "subset": "dot",
    "alg": "U' f R U R' U' f' U' F R U R' U' F'"
  },
  {
    "id": "oll-4",
    "name": "OLL 4",
    "subset": "dot",
    "alg": "U' f R U R' U' f' U F R U R' U' F'"
  },
  {
    "id": "oll-5",
    "name": "OLL 5",
    "subset": "square",
    "alg": "r' U2 R U R' U r"
  },
  {
    "id": "oll-6",
    "name": "OLL 6",
    "subset": "square",
    "alg": "r U2 R' U' R U' r'"
  },
  {
    "id": "oll-7",
    "name": "OLL 7",
    "subset": "lightning-bolt",
    "alg": "r U R' U R U2 r'"
  },
  {
    "id": "oll-8",
    "name": "OLL 8",
    "subset": "lightning-bolt",
    "alg": "U2 r' U' R U' R' U2 r"
  },
  {
    "id": "oll-9",
    "name": "OLL 9",
    "subset": "fish-shape",
    "alg": "U R U R' U' R' F R2 U R' U' F'"
  },
  {
    "id": "oll-10",
    "name": "OLL 10",
    "subset": "fish-shape",
    "alg": "R U R' U R' F R F' R U2 R'"
  },
  {
    "id": "oll-11",
    "name": "OLL 11",
    "subset": "lightning-bolt",
    "alg": "M R U R' U R U2 R' U M'"
  },
  {
    "id": "oll-12",
    "name": "OLL 12",
    "subset": "lightning-bolt",
    "alg": "U' M' R' U' R U' R' U2 R U' M"
  },
  {
    "id": "oll-13",
    "name": "OLL 13",
    "subset": "knight-shape",
    "alg": "r U' r' U' r U r' F' U F"
  },
  {
    "id": "oll-14",
    "name": "OLL 14",
    "subset": "knight-shape",
    "alg": "R' F R U R' F' R F U' F'"
  },
  {
    "id": "oll-15",
    "name": "OLL 15",
    "subset": "knight-shape",
    "alg": "r' U' r R' U' R U r' U r"
  },
  {
    "id": "oll-16",
    "name": "OLL 16",
    "subset": "knight-shape",
    "alg": "r U r' R U R' U' r U' r'"
  },
  {
    "id": "oll-17",
    "name": "OLL 17",
    "subset": "dot",
    "alg": "R U R' U R' F R F' U2 R' F R F'"
  },
  {
    "id": "oll-18",
    "name": "OLL 18",
    "subset": "dot",
    "alg": "U R U2 R2 F R F' U2 M' U R U' r'"
  },
  {
    "id": "oll-19",
    "name": "OLL 19",
    "subset": "dot",
    "alg": "M U R U R' U' M' R' F R F'"
  },
  {
    "id": "oll-20",
    "name": "OLL 20",
    "subset": "dot",
    "alg": "r U R' U' M2 U R U' R' U' M'"
  },
  {
    "id": "oll-21",
    "name": "OLL 21",
    "subset": "cross",
    "alg": "R U R' U R U' R' U R U2 R'"
  },
  {
    "id": "oll-22",
    "name": "OLL 22",
    "subset": "cross",
    "alg": "R' U2 R2 U R2 U R2 U2 R'"
  },
  {
    "id": "oll-23",
    "name": "OLL 23",
    "subset": "cross",
    "alg": "R2 D R' U2 R D' R' U2 R'"
  },
  {
    "id": "oll-24",
    "name": "OLL 24",
    "subset": "cross",
    "alg": "r U R' U' r' F R F'"
  },
  {
    "id": "oll-25",
    "name": "OLL 25",
    "subset": "cross",
    "alg": "U F' r U R' U' r' F R"
  },
  {
    "id": "oll-26",
    "name": "OLL 26",
    "subset": "cross",
    "alg": "U R U2 R' U' R U' R'"
  },
  {
    "id": "oll-27",
    "name": "OLL 27",
    "subset": "cross",
    "alg": "R U R' U R U2 R'"
  },
  {
    "id": "oll-28",
    "name": "OLL 28",
    "subset": "corners-oriented",
    "alg": "r U R' U' M U R U' R'"
  },
  {
    "id": "oll-29",
    "name": "OLL 29",
    "subset": "awkward-shape",
    "alg": "U R U R' U' R U' R' F' U' F R U R'"
  },
  {
    "id": "oll-30",
    "name": "OLL 30",
    "subset": "awkward-shape",
    "alg": "U2 F U R U2 R' U' R U2 R' U' F'"
  },
  {
    "id": "oll-31",
    "name": "OLL 31",
    "subset": "p-shape",
    "alg": "R' U' F U R U' R' F' R"
  },
  {
    "id": "oll-32",
    "name": "OLL 32",
    "subset": "p-shape",
    "alg": "S R U R' U' R' F R f'"
  },
  {
    "id": "oll-33",
    "name": "OLL 33",
    "subset": "t-shape",
    "alg": "R U R' U' R' F R F'"
  },
  {
    "id": "oll-34",
    "name": "OLL 34",
    "subset": "c-shape",
    "alg": "U2 R U R2 U' R' F R U R U' F'"
  },
  {
    "id": "oll-35",
    "name": "OLL 35",
    "subset": "fish-shape",
    "alg": "R U2 R2 F R F' R U2 R'"
  },
  {
    "id": "oll-36",
    "name": "OLL 36",
    "subset": "w-shape",
    "alg": "U2 L' U' L U' L' U L U L F' L' F"
  },
  {
    "id": "oll-37",
    "name": "OLL 37",
    "subset": "fish-shape",
    "alg": "F R U' R' U' R U R' F'"
  },
  {
    "id": "oll-38",
    "name": "OLL 38",
    "subset": "w-shape",
    "alg": "R U R' U R U' R' U' R' F R F'"
  },
  {
    "id": "oll-39",
    "name": "OLL 39",
    "subset": "lightning-bolt",
    "alg": "U L F' L' U' L U F U' L'"
  },
  {
    "id": "oll-40",
    "name": "OLL 40",
    "subset": "lightning-bolt",
    "alg": "U R' F R U R' U' F' U R"
  },
  {
    "id": "oll-41",
    "name": "OLL 41",
    "subset": "awkward-shape",
    "alg": "U2 R U R' U R U2 R' F R U R' U' F'"
  },
  {
    "id": "oll-42",
    "name": "OLL 42",
    "subset": "awkward-shape",
    "alg": "R' U' R U' R' U2 R F R U R' U' F'"
  },
  {
    "id": "oll-43",
    "name": "OLL 43",
    "subset": "p-shape",
    "alg": "U R' U' F' U F R"
  },
  {
    "id": "oll-44",
    "name": "OLL 44",
    "subset": "p-shape",
    "alg": "f R U R' U' f'"
  },
  {
    "id": "oll-45",
    "name": "OLL 45",
    "subset": "t-shape",
    "alg": "F R U R' U' F'"
  },
  {
    "id": "oll-46",
    "name": "OLL 46",
    "subset": "c-shape",
    "alg": "R' U' R' F R F' U R"
  },
  {
    "id": "oll-47",
    "name": "OLL 47",
    "subset": "l-shape",
    "alg": "F' L' U' L U L' U' L U F"
  },
  {
    "id": "oll-48",
    "name": "OLL 48",
    "subset": "l-shape",
    "alg": "F R U R' U' R U R' U' F'"
  },
  {
    "id": "oll-49",
    "name": "OLL 49",
    "subset": "l-shape",
    "alg": "U2 r U' r2 U r2 U r2 U' r"
  },
  {
    "id": "oll-50",
    "name": "OLL 50",
    "subset": "l-shape",
    "alg": "r' U r2 U' r2 U' r2 U r'"
  },
  {
    "id": "oll-51",
    "name": "OLL 51",
    "subset": "i-shape",
    "alg": "f R U R' U' R U R' U' f'"
  },
  {
    "id": "oll-52",
    "name": "OLL 52",
    "subset": "i-shape",
    "alg": "R U R' U R U' B U' B' R'"
  },
  {
    "id": "oll-53",
    "name": "OLL 53",
    "subset": "l-shape",
    "alg": "r' U2 R U R' U' R U R' U r"
  },
  {
    "id": "oll-54",
    "name": "OLL 54",
    "subset": "l-shape",
    "alg": "r U2 R' U' R U R' U' R U' r'"
  },
  {
    "id": "oll-55",
    "name": "OLL 55",
    "subset": "i-shape",
    "alg": "R U2 R2 U' R U' R' U2 F R F'"
  },
  {
    "id": "oll-56",
    "name": "OLL 56",
    "subset": "i-shape",
    "alg": "r U r' U R U' R' U R U' R' r U' r'"
  },
  {
    "id": "oll-57",
    "name": "OLL 57",
    "subset": "corners-oriented",
    "alg": "R U R' U' M' U R U' r'"
  }
];

export const PLL = [
  {
    "id": "aa",
    "name": "Aa Permutation",
    "subset": "edge-swap",
    "alg": "x R2 D2 R U R' D2 R U' R x'"
  },
  {
    "id": "ab",
    "name": "Ab Permutation",
    "subset": "edge-swap",
    "alg": "x R' U R' D2 R U' R' D2 R2 x'"
  },
  {
    "id": "e",
    "name": "E Permutation",
    "subset": "edge-swap",
    "alg": "x' D R U R' D' R U' R' D R U' R' D' R U R' x"
  },
  {
    "id": "f",
    "name": "F Permutation",
    "subset": "adjacent-swap",
    "alg": "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R"
  },
  {
    "id": "ga",
    "name": "Ga Permutation",
    "subset": "adjacent-swap",
    "alg": "R' U' R D' U R2 U R' U R U' R U' R2 D"
  },
  {
    "id": "gb",
    "name": "Gb Permutation",
    "subset": "adjacent-swap",
    "alg": "R2 U R' U R' U' R U' R2 D U' R' U R D'"
  },
  {
    "id": "gc",
    "name": "Gc Permutation",
    "subset": "adjacent-swap",
    "alg": "D' R U R' U' D R2 U' R U' R' U R' U R2"
  },
  {
    "id": "gd",
    "name": "Gd Permutation",
    "subset": "adjacent-swap",
    "alg": "R2 U' R U' R U R' U R2 D' U R U' R' D"
  },
  {
    "id": "h",
    "name": "H Permutation",
    "subset": "epll",
    "alg": "M2 U M2 U2 M2 U M2"
  },
  {
    "id": "ja",
    "name": "Ja Permutation",
    "subset": "adjacent-swap",
    "alg": "L' R' U2 R U R' U2 L U' R"
  },
  {
    "id": "jb",
    "name": "Jb Permutation",
    "subset": "adjacent-swap",
    "alg": "R U R2 F' R U R U' R' F R U' R'"
  },
  {
    "id": "na",
    "name": "Na Permutation",
    "subset": "diagonal-swap",
    "alg": "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'"
  },
  {
    "id": "nb",
    "name": "Nb Permutation",
    "subset": "diagonal-swap",
    "alg": "R' U R U' R' F' U' F R U R' F R' F' R U' R"
  },
  {
    "id": "ra",
    "name": "Ra Permutation",
    "subset": "adjacent-swap",
    "alg": "R U2 R D R' U R D' R' U' R' U R U R'"
  },
  {
    "id": "rb",
    "name": "Rb Permutation",
    "subset": "adjacent-swap",
    "alg": "R' U R U R' U' R' D' R U R' D R U2 R"
  },
  {
    "id": "t",
    "name": "T Permutation",
    "subset": "adjacent-swap",
    "alg": "R U R' U' R' F R2 U' R' U' R U R' F'"
  },
  {
    "id": "ua",
    "name": "Ua Permutation",
    "subset": "epll",
    "alg": "M2 U' M' U2 M U' M2"
  },
  {
    "id": "ub",
    "name": "Ub Permutation",
    "subset": "epll",
    "alg": "M2 U M' U2 M U M2"
  },
  {
    "id": "v",
    "name": "V Permutation",
    "subset": "diagonal-swap",
    "alg": "D2 R' U R D' R2 U' R' U R' U R' D' R U2 R'"
  },
  {
    "id": "U",
    "name": "Y Permutation",
    "subset": "diagonal-swap",
    "alg": "F R' F' R U R U' R' F R U' R' U R U R' F'"
  },
  {
    "id": "z",
    "name": "Z Permutation",
    "subset": "epll",
    "alg": "M U2 M2 U2 M U' M2 U' M2"
  }
];
